turn other tests back on

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -12,49 +12,49 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  # build_and_detekt:
-  #   if: github.repository == 'meshtastic/Meshtastic-Android' && github.head_ref != 'scheduled-updates'
-  #   uses: ./.github/workflows/reusable-android-build.yml
-  #   secrets:
-  #     GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
-  #   # inputs.upload_artifacts defaults to true, so no need to specify for PRs
+  build_and_detekt:
+    if: github.repository == 'meshtastic/Meshtastic-Android' && github.head_ref != 'scheduled-updates'
+    uses: ./.github/workflows/reusable-android-build.yml
+    secrets:
+      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
+    # inputs.upload_artifacts defaults to true, so no need to specify for PRs
 
-  # androidTest:
-  #   # Assuming androidTest should also only run for the main repository
-  #   if: github.repository == 'meshtastic/Meshtastic-Android' && github.head_ref != 'scheduled-updates'
-  #   uses: ./.github/workflows/reusable-android-test.yml
-  #   with:
-  #     api_levels: '[35]' # Run only on API 35 for PRs
-  #     # upload_artifacts defaults to true, so no need to explicitly set
-  #   secrets:
-  #     GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
+  androidTest:
+    # Assuming androidTest should also only run for the main repository
+    if: github.repository == 'meshtastic/Meshtastic-Android' && github.head_ref != 'scheduled-updates'
+    uses: ./.github/workflows/reusable-android-test.yml
+    with:
+      api_levels: '[35]' # Run only on API 35 for PRs
+      # upload_artifacts defaults to true, so no need to explicitly set
+    secrets:
+      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
 
-  # check-workflow-status:
-  #   name: Check Workflow Status
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     [
-  #       build_and_detekt,
-  #       androidTest
-  #     ]
-  #   if: always()
-  #   steps:
-  #     - name: Check Workflow Status
-  #       run: |
-  #         exit_on_result() {
-  #           if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
-  #             echo "Job '$1' failed or was cancelled."
-  #             exit 1
-  #           fi
-  #         }
-  #         exit_on_result "build_and_detekt" "${{ needs.build_and_detekt.result }}"
-  #         exit_on_result "androidTest" "${{ needs.androidTest.result }}"
+  check-workflow-status:
+    name: Check Workflow Status
+    runs-on: ubuntu-latest
+    needs:
+      [
+        build_and_detekt,
+        androidTest
+      ]
+    if: always()
+    steps:
+      - name: Check Workflow Status
+        run: |
+          exit_on_result() {
+            if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
+              echo "Job '$1' failed or was cancelled."
+              exit 1
+            fi
+          }
+          exit_on_result "build_and_detekt" "${{ needs.build_and_detekt.result }}"
+          exit_on_result "androidTest" "${{ needs.androidTest.result }}"
 
   check-label:
     runs-on: ubuntu-latest
     needs:
       [
-        # check-workflow-status,
+        check-workflow-status,
       ]
     steps:
       - name: Check for PR labels
